const express = require("express");

const router = express.Router();

// import middleware
const checkRole = require("../middlewares/check-role");

// import controllers
const AgamaController = require("../controllers/api-feeder/agama");
const NegaraController = require("../controllers/api-feeder/negara");
const WilayahController = require("../controllers/api-feeder/wilayah");
const PerguruanTinggiController = require("../controllers/api-feeder/perguruan-tinggi");
const ProfilPTController = require("../controllers/api-feeder/profil-pt");
const JalurMasukController = require("../controllers/api-feeder/jalur-masuk");
const JenisPendaftaranController = require("../controllers/api-feeder/jenis-pendaftaran");
const JenisTinggalController = require("../controllers/api-feeder/jenis-tinggal");
const AlatTransportasiController = require("../controllers/api-feeder/alat-transportasi");
const StatusMahasiswaController = require("../controllers/api-feeder/status-mahasiswa");
const KebutuhanKhususController = require("../controllers/api-feeder/kebutuhan-khusus");
const PenghasilanController = require("../controllers/api-feeder/penghasilan");
const JenisSMSController = require("../controllers/api-feeder/jenis-sms");
const LembagaPengangkatanController = require("../controllers/api-feeder/lembaga-pengangkatan");
const StatusKeaktifanPegawaiController = require("../controllers/api-feeder/status-keaktifan-pegawai");
const PangkatGolonganController = require("../controllers/api-feeder/pangkat-golongan");
const PekerjaanController = require("../controllers/api-feeder/pekerjaan");
const DosenController = require("../controllers/api-feeder/dosen");
const BiodataDosenController = require("../controllers/api-feeder/biodata-dosen");
const JenjangPendidikanController = require("../controllers/api-feeder/jenjang-pendidikan");
const ProdiController = require("../controllers/api-feeder/prodi");
const PeriodeController = require("../controllers/api-feeder/periode");
const JenisSubstansiController = require("../controllers/api-feeder/jenis-substansi");
const SubstansiController = require("../controllers/api-feeder/substansi");
const SubstansiKuliahController = require("../controllers/api-feeder/substansi-kuliah");
const MataKuliahController = require("../controllers/api-feeder/mata-kuliah");
const TahunAjaranController = require("../controllers/api-feeder/tahun-ajaran");
const FakultasController = require("../controllers/api-feeder/fakultas");
const SemesterController = require("../controllers/api-feeder/semester");
const KurikulumController = require("../controllers/api-feeder/kurikulum");
const DetailKurikulumController = require("../controllers/api-feeder/detail-kurikulum");
const PenugasanDosenController = require("../controllers/api-feeder/penugasan-dosen");
const MatkulKurikulumController = require("../controllers/api-feeder/matkul-kurikulum");
const KelasKuliahController = require("../controllers/api-feeder/kelas-kuliah");
const DetailKelasKuliahController = require("../controllers/api-feeder/detail-kelas-kuliah");
const PerhitunganSKSController = require("../controllers/api-feeder/perhitungan-sks");
const JenisKeluarController = require("../controllers/api-feeder/jenis-keluar");
const PembiayaanController = require("../controllers/api-feeder/pembiayaan");
const BidangMinatController = require("../controllers/api-feeder/bidang-minat");
const SkalaNilaiProdiController = require("../controllers/api-feeder/skala-nilai-prodi");
const PeriodePerkuliahanController = require("../controllers/api-feeder/periode-perkuliahan");
const DetailPeriodePerkuliahanController = require("../controllers/api-feeder/detail-periode-perkuliahan");
const JenisAktivitasMahasiswaController = require("../controllers/api-feeder/jenis-aktivitas-mahasiswa");
const AktivitasMahasiswaController = require("../controllers/api-feeder/aktivitas-mahasiswa");
const BiodataMahasiswaController = require("../controllers/api-feeder/biodata-mahasiswa");
const MahasiswaController = require("../controllers/api-feeder/mahasiswa");
const RiwayatPendidikanMahasiswaController = require("../controllers/api-feeder/riwayat-pendidikan-mahasiswa");
const DetailNilaiPerkuliahanKelasController = require("../controllers/api-feeder/detail-nilai-perkuliahan-kelas");
const RiwayatNilaiMahasiswaController = require("../controllers/api-feeder/riwayat-nilai-mahasiswa");
const PesertaKelasKuliahController = require("../controllers/api-feeder/peserta-kelas-kuliah");
const PerkuliahanMahasiswaController = require("../controllers/api-feeder/perkuliahan-mahasiswa");
const DetailPerkuliahanMahasiswaController = require("../controllers/api-feeder/detail-perkuliahan-mahasiswa");
const KRSMahasiswaController = require("../controllers/api-feeder/krs-mahasiswa");
const AktivitasKuliahMahasiswaController = require("../controllers/api-feeder/aktivitas-kuliah-mahasiswa");
const AnggotaAktivitasMahasiswaController = require("../controllers/api-feeder/anggota-aktivitas-mahasiswa");
const KonversiKampusMerdekaController = require("../controllers/api-feeder/konversi-kampus-merdeka");
const TranskripMahasiswaController = require("../controllers/api-feeder/transkrip-mahasiswa");
const RekapJumlahMahasiswaController = require("../controllers/api-feeder/rekap-jumlah-mahasiswa");
const RekapKHSMahasiswaController = require("../controllers/api-feeder/rekap-khs-mahasiswa");
const RekapKRSMahasiswaController = require("../controllers/api-feeder/rekap-krs-mahasiswa");
const DataLengkapMahasiswaProdiController = require("../controllers/api-feeder/data-lengkap-mahasiswa-prodi");
const JenisEvaluasiControllerController = require("../controllers/api-feeder/jenis-evaluasi");
const DosenPengajarKelasKuliahController = require("../controllers/api-feeder/dosen-pengajar-kelas-kuliah");
const KategoriKegiatanController = require("../controllers/api-feeder/kategori-kegiatan");
const MahasiswaBimbinganDosenController = require("../controllers/api-feeder/mahasiswa-bimbingan-dosen");
const UjiMahasiswaController = require("../controllers/api-feeder/uji-mahasiswa");

// controller for api-feeder-update (data)
const DetailNilaiPerkuliahanKelasUpdateController = require("../controllers/api-feeder-update/detail-nilai-perkuliahan-kelas");
const RiwayatNilaiMahasiswaUpdateController = require("../controllers/api-feeder-update/riwayat-nilai-mahasiswa");

// all routes
router.get("/get-agama", checkRole(["admin"]), AgamaController.getAgama);
router.get("/get-negara", checkRole(["admin"]), NegaraController.getNegara);
router.get("/get-wilayah", checkRole(["admin"]), WilayahController.getWilayah);
router.get("/get-all-pt", checkRole(["admin"]), PerguruanTinggiController.getAllPerguruanTinggi);
router.get("/get-profil-pt", checkRole(["admin"]), ProfilPTController.getProfilPT);
router.get("/get-jalur-masuk", checkRole(["admin"]), JalurMasukController.getJalurMasuk);
router.get("/get-jenis-pendaftaran", checkRole(["admin"]), JenisPendaftaranController.getJenisPendaftaran);
router.get("/get-jenis-tinggal", checkRole(["admin"]), JenisTinggalController.getJenisTinggal);
router.get("/get-alat-transportasi", checkRole(["admin"]), AlatTransportasiController.getAlatTransportasi);
router.get("/get-status-mahasiswa", checkRole(["admin"]), StatusMahasiswaController.getStatusMahasiswa);
router.get("/get-kebutuhan-khusus", checkRole(["admin"]), KebutuhanKhususController.getKebutuhanKhusus);
router.get("/get-penghasilan", checkRole(["admin"]), PenghasilanController.getPenghasilan);
router.get("/get-jenis-sms", checkRole(["admin"]), JenisSMSController.getJenisSms);
router.get("/get-lembaga-pengangkatan", checkRole(["admin"]), LembagaPengangkatanController.getLembagaPengangkatan);
router.get("/get-status-keaktifan-pegawai", checkRole(["admin"]), StatusKeaktifanPegawaiController.getStatusKeaktifanPegawai);
router.get("/get-pangkat-golongan", checkRole(["admin"]), PangkatGolonganController.getPangkatGolongan);
router.get("/get-pekerjaan", checkRole(["admin"]), PekerjaanController.getPekerjaan);
router.get("/get-dosen", checkRole(["admin"]), DosenController.getDosen);
router.get("/get-biodata-dosen", checkRole(["admin"]), BiodataDosenController.getBiodataDosen);
router.get("/get-jenjang-pendidikan", checkRole(["admin"]), JenjangPendidikanController.getJenjangPendidikan);
router.get("/get-prodi", checkRole(["admin"]), ProdiController.getProdi);
router.get("/get-periode", checkRole(["admin"]), PeriodeController.getPeriode);
router.get("/get-jenis-substansi", checkRole(["admin"]), JenisSubstansiController.getJenisSubstansi);
router.get("/get-substansi", checkRole(["admin"]), SubstansiController.getSubstansi);
router.get("/get-substansi-kuliah", checkRole(["admin"]), SubstansiKuliahController.getSubstansiKuliah);
router.get("/get-mata-kuliah", checkRole(["admin"]), MataKuliahController.getMataKuliah);
router.get("/get-tahun-ajaran", checkRole(["admin"]), TahunAjaranController.getTahunAjaran);
router.get("/get-fakultas", checkRole(["admin"]), FakultasController.getFakultas);
router.get("/get-semester", checkRole(["admin"]), SemesterController.getSemester);
router.get("/get-kurikulum", checkRole(["admin"]), KurikulumController.getKurikulum);
router.get("/get-detail-kurikulum", checkRole(["admin"]), DetailKurikulumController.getDetailKurikulum);
router.get("/get-penugasan-dosen", checkRole(["admin"]), PenugasanDosenController.getPenugasanDosen);
router.get("/get-matkul-kurikulum", checkRole(["admin"]), MatkulKurikulumController.getMatkulKurikulum);
router.get("/get-kelas-kuliah", checkRole(["admin"]), KelasKuliahController.getKelasKuliah);
router.get("/get-detail-kelas-kuliah", checkRole(["admin"]), DetailKelasKuliahController.getDetailKelasKuliah);
router.get("/get-perhitungan-sks", checkRole(["admin"]), PerhitunganSKSController.getPerhitunganSKS);
router.get("/get-jenis-keluar", checkRole(["admin"]), JenisKeluarController.getJenisKeluar);
router.get("/get-pembiayaan", checkRole(["admin"]), PembiayaanController.getPembiayaan);
router.get("/get-bidang-minat", checkRole(["admin"]), BidangMinatController.getBidangMinat);
router.get("/get-skala-nilai-prodi", checkRole(["admin"]), SkalaNilaiProdiController.getSkalaNilaiProdi);
router.get("/get-periode-perkuliahan", checkRole(["admin"]), PeriodePerkuliahanController.getPeriodePerkuliahan);
router.get("/get-detail-periode-perkuliahan", checkRole(["admin"]), DetailPeriodePerkuliahanController.getDetailPeriodePerkuliahan);
router.get("/get-jenis-aktivitas-mahasiswa", checkRole(["admin"]), JenisAktivitasMahasiswaController.getJenisAktivitasMahasiswa);
router.get("/get-aktivitas-mahasiswa", checkRole(["admin"]), AktivitasMahasiswaController.getAktivitasMahasiswa);
router.get("/get-biodata-mahasiswa", checkRole(["admin"]), BiodataMahasiswaController.getBiodataMahasiswa);
router.get("/get-mahasiswa", checkRole(["admin"]), MahasiswaController.getMahasiswa);
router.get("/get-riwayat-pendidikan-mahasiswa", checkRole(["admin"]), RiwayatPendidikanMahasiswaController.getRiwayatPendidikanMahasiswa);
router.get("/get-detail-nilai-perkuliahan-kelas", checkRole(["admin"]), DetailNilaiPerkuliahanKelasController.getDetailNilaiPerkuliahanKelas);
router.get("/get-riwayat-nilai-mahasiswa", checkRole(["admin"]), RiwayatNilaiMahasiswaController.getRiwayatNilaiMahasiswa);
router.get("/get-peserta-kelas-kuliah", checkRole(["admin"]), PesertaKelasKuliahController.getPesertaKelasKuliah);
router.get("/get-perkuliahan-mahasiswa", checkRole(["admin"]), PerkuliahanMahasiswaController.getPerkuliahanMahasiswa);
router.get("/get-detail-perkuliahan-mahasiswa", checkRole(["admin"]), DetailPerkuliahanMahasiswaController.getDetailPerkuliahanMahasiswa);
router.get("/get-krs-mahasiswa", checkRole(["admin"]), KRSMahasiswaController.getKRSMahasiswa);
router.get("/get-aktivitas-kuliah-mahasiswa", checkRole(["admin"]), AktivitasKuliahMahasiswaController.getAktivitasKuliahMahasiswa);
router.get("/get-anggota-aktivitas-mahasiswa", checkRole(["admin"]), AnggotaAktivitasMahasiswaController.getAnggotaAktivitasMahasiswa);
router.get("/get-konversi-kampus-merdeka", checkRole(["admin"]), KonversiKampusMerdekaController.getKonversiKampusMerdeka);
router.get("/get-transkrip-mahasiswa", checkRole(["admin"]), TranskripMahasiswaController.getTranskripMahasiswa);
router.get("/get-rekap-jumlah-mahasiswa", checkRole(["admin"]), RekapJumlahMahasiswaController.getRekapJumlahMahasiswa);
router.get("/get-rekap-khs-mahasiswa", checkRole(["admin"]), RekapKHSMahasiswaController.getRekapKHSMahasiswa);
router.get("/get-rekap-krs-mahasiswa", checkRole(["admin"]), RekapKRSMahasiswaController.getRekapKRSMahasiswa);
router.get("/get-data-lengkap-mahasiswa-prodi", checkRole(["admin"]), DataLengkapMahasiswaProdiController.getDataLengkapMahasiswaProdi);
router.get("/get-jenis-evaluasi", checkRole(["admin"]), JenisEvaluasiControllerController.getJenisEvaluasi);
router.get("/get-dosen-pengajar-kelas-kuliah", checkRole(["admin"]), DosenPengajarKelasKuliahController.getDosenPengajarKelasKuliah);
router.get("/get-kategori-kegiatan", checkRole(["admin"]), KategoriKegiatanController.getKategoriKegiatan);
router.get("/get-mahasiswa-bimbingan-dosen", checkRole(["admin"]), MahasiswaBimbinganDosenController.getMahasiswaBimbinganDosen);
router.get("/get-uji-mahasiswa", checkRole(["admin"]), UjiMahasiswaController.getUjiMahasiswa);

// routes for api-feeder-update (data)
router.get("/update-detail-nilai-perkuliahan-kelas", checkRole(["admin"]), DetailNilaiPerkuliahanKelasUpdateController.getDetailNilaiPerkuliahanKelas);
router.get("/update-riwayat-nilai-mahasiswa", checkRole(["admin"]), RiwayatNilaiMahasiswaUpdateController.getRiwayatNilaiMahasiswa);

module.exports = router;
